{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "aaptcompiler",
    "version": "9.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "aaptcompiler-9.2.1.jar",
          "url": "aaptcompiler-9.2.1.jar",
          "size": 493910,
          "sha512": "b2e0486bc749f5e7048f7dd1644b6fa3dbe9b607151302e7b7df36e4d16e482355c0a2d69ac3e1ab4b3b5c7ad47773b9c062ff27d660cd77185bdf2024e7e536",
          "sha256": "45c46bfd758de568b8118a168d56863f87566188692c9e80c1b77fff8c6a3620",
          "sha1": "f365cc4e7fda1936ac58bf9ab2c7917cd6169536",
          "md5": "40a5b83a5c4bc343d2c8f8566e2c7221"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "aapt2-proto",
          "version": {
            "requires": "9.2.1-15009934"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "32.2.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "32.2.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.25.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-jre"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "aaptcompiler-9.2.1.jar",
          "url": "aaptcompiler-9.2.1.jar",
          "size": 493910,
          "sha512": "b2e0486bc749f5e7048f7dd1644b6fa3dbe9b607151302e7b7df36e4d16e482355c0a2d69ac3e1ab4b3b5c7ad47773b9c062ff27d660cd77185bdf2024e7e536",
          "sha256": "45c46bfd758de568b8118a168d56863f87566188692c9e80c1b77fff8c6a3620",
          "sha1": "f365cc4e7fda1936ac58bf9ab2c7917cd6169536",
          "md5": "40a5b83a5c4bc343d2c8f8566e2c7221"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aaptcompiler-9.2.1-javadoc.jar",
          "url": "aaptcompiler-9.2.1-javadoc.jar",
          "size": 81065,
          "sha512": "50b2a55c05905cfce9f4d49cab238bd811f2c976ceabb8c5c9980d3a4445a9da09fea2c1ca3b726ea163f612412eceef07aaa7de45881269ce6417ecce715f46",
          "sha256": "9c7e586cbe406a4e730c012ea10d5b139baee3c2d86186b909e832e9268d0aa7",
          "sha1": "3736bd20a12416d959b4ab7b3cef6ef31f29d684",
          "md5": "eded224dd6079aac42bf31fdcf1a2363"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aaptcompiler-9.2.1-sources.jar",
          "url": "aaptcompiler-9.2.1-sources.jar",
          "size": 152179,
          "sha512": "a2ae0ad4bc6f4d23679ea08b0c5a8fd825bf1a781a9221f995bf363422c1d83d52e8c9b8a036dd9bc253271c4e474c516c982bbe817d51e9ffc4b8c8afc78d81",
          "sha256": "60237e90334d6db447c37a825e35f7ff83337c1542ea0e9f0aee06b6e0484336",
          "sha1": "5fc1181f1cb14ecbe416aae29b74a1bbe33c232c",
          "md5": "e899cd9ba827d7c9f42c76e904de6d5b"
        }
      ]
    }
  ]
}
