{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "manifest-merger",
    "version": "32.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "manifest-merger-32.2.1.jar",
          "url": "manifest-merger-32.2.1.jar",
          "size": 269485,
          "sha512": "8da7f79be40bdef609cb4e0a12082a69c9df7303833be8fc90e8ebe7f961c32ffae52dcd89e6d896c850863dadcc6eb440a7a6e129b029a2d27954f7990107b8",
          "sha256": "a21fdf8d76f3627391c92c75746a8bff9e1fb8e53a1a3cce384edd81bae687b2",
          "sha1": "e09c366b67603825ea0540d935cedab0e001cc70",
          "md5": "f063579ce4d893be642aa2f45a85e3e4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "32.2.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "32.2.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "32.2.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "manifest-merger-32.2.1.jar",
          "url": "manifest-merger-32.2.1.jar",
          "size": 269485,
          "sha512": "8da7f79be40bdef609cb4e0a12082a69c9df7303833be8fc90e8ebe7f961c32ffae52dcd89e6d896c850863dadcc6eb440a7a6e129b029a2d27954f7990107b8",
          "sha256": "a21fdf8d76f3627391c92c75746a8bff9e1fb8e53a1a3cce384edd81bae687b2",
          "sha1": "e09c366b67603825ea0540d935cedab0e001cc70",
          "md5": "f063579ce4d893be642aa2f45a85e3e4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "manifest-merger-32.2.1-javadoc.jar",
          "url": "manifest-merger-32.2.1-javadoc.jar",
          "size": 260910,
          "sha512": "efbaf5a6b29c255851b7c5be9c750636ef51c9226092ee287bf6a81ea4f648f528b4110401e9a759b46a6fef667be0a55ed84faeea6e42bfcea0f836a79290ed",
          "sha256": "0d460e614b68e099d4ec127e67484a1d31b6ba7a609b485e9af277cb2b9343b0",
          "sha1": "833fcad5a4a2154b6eb03217f89951f530a9ae45",
          "md5": "a9be39331c929f8e2cc2392a772c5b59"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "manifest-merger-32.2.1-sources.jar",
          "url": "manifest-merger-32.2.1-sources.jar",
          "size": 235996,
          "sha512": "9303c8e948b7b20c0de63e1ed355e9e0b60edfc0a3525c5dffdaf00a11c6c8659df7c74a884455e2d3ce698a2d39c149f92c56fed4d67ecd9a192fa96ecad826",
          "sha256": "b7f3deb356146cb650afe011113fbc05ecaeea5c10c5400059cc25e4304aaa2f",
          "sha1": "dc796821a18f4a6c19aeca9b9e763e9a1cae0403",
          "md5": "19e39abebb71b5175f6fc6b0863f107a"
        }
      ]
    }
  ]
}
