{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "gradle-api",
    "version": "9.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle-common-api",
          "version": {
            "requires": "9.2.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-api-9.2.1.jar",
          "url": "gradle-api-9.2.1.jar",
          "size": 411070,
          "sha512": "f648f54643979c19a97572cc13856a0c4e35bbb6d1e4f45dede875fd609949a278e40a28de2684cc27a2db99dafdec8e2e20255b1ce5873bc18f74cab8561385",
          "sha256": "fdb67e10cd147dcddede285e6258f586574370fdbbe440bab5e8283e41c3d881",
          "sha1": "21e0ccc5b81ae7b6f1a07e1936e33b0bab648117",
          "md5": "2b728b1646211872e2ef9b1eb40ddf88"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "9.2.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-jre"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-common-api",
          "version": {
            "requires": "9.2.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "9.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-api-9.2.1.jar",
          "url": "gradle-api-9.2.1.jar",
          "size": 411070,
          "sha512": "f648f54643979c19a97572cc13856a0c4e35bbb6d1e4f45dede875fd609949a278e40a28de2684cc27a2db99dafdec8e2e20255b1ce5873bc18f74cab8561385",
          "sha256": "fdb67e10cd147dcddede285e6258f586574370fdbbe440bab5e8283e41c3d881",
          "sha1": "21e0ccc5b81ae7b6f1a07e1936e33b0bab648117",
          "md5": "2b728b1646211872e2ef9b1eb40ddf88"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-api-9.2.1-javadoc.jar",
          "url": "gradle-api-9.2.1-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-api-9.2.1-sources.jar",
          "url": "gradle-api-9.2.1-sources.jar",
          "size": 383720,
          "sha512": "89152919fab41fbb083a02831bcedc8ee1aa96e2a126a8c3ac1a34e9e67a9182c22e57034b149f99166c9982143427762dcdcf2d4767a1a7b15489b207622d50",
          "sha256": "c50d6746ddb5dc74205043ddab77b5d76bd448a4731f012ab5061a89dc86da5c",
          "sha1": "aaa7db1d964bcf20ee95e7ccbae935ee83aa7562",
          "md5": "64c8fce5571e4fec80b2e215bd891dca"
        }
      ]
    }
  ]
}
