{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "builder",
    "version": "9.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "32.2.1"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "9.2.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "9.2.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "9.2.1"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-9.2.1.jar",
          "url": "builder-9.2.1.jar",
          "size": 17596356,
          "sha512": "3bae21b54b8b4278bcbb6d5367d7c9ec5bc824b30542f01cd35d4efa75233c6f2347befa4f4b3206f62d7a155a6dae75ec852ead2af27e5b2bb54ff8b46e2f01",
          "sha256": "091274bf71a4e29d823a54fefb4b59643f4abc23ef15b652b787d1565280bdb0",
          "sha1": "e8ef7f9072cd990708591c54128fd6c6dc42ae7d",
          "md5": "2e43e76e58abaef60dce7a82f9059d8c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "9.2.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "9.2.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "32.2.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "32.2.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "32.2.1"
          }
        },
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "32.2.1"
          }
        },
        {
          "group": "com.android",
          "module": "signflinger",
          "version": {
            "requires": "9.2.1"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "protos",
          "version": {
            "requires": "32.2.1"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "tracker",
          "version": {
            "requires": "32.2.1"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "32.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk18on",
          "version": {
            "requires": "1.79"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.79"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.9"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "32.2.1"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "9.2.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "9.2.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "9.2.1"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-9.2.1.jar",
          "url": "builder-9.2.1.jar",
          "size": 17596356,
          "sha512": "3bae21b54b8b4278bcbb6d5367d7c9ec5bc824b30542f01cd35d4efa75233c6f2347befa4f4b3206f62d7a155a6dae75ec852ead2af27e5b2bb54ff8b46e2f01",
          "sha256": "091274bf71a4e29d823a54fefb4b59643f4abc23ef15b652b787d1565280bdb0",
          "sha1": "e8ef7f9072cd990708591c54128fd6c6dc42ae7d",
          "md5": "2e43e76e58abaef60dce7a82f9059d8c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-9.2.1-javadoc.jar",
          "url": "builder-9.2.1-javadoc.jar",
          "size": 338902,
          "sha512": "b8fb41bb3af93a3187f8e8da17d65a0acb9d84fcd37dc35da2072c5d84a3b0fc29cd848eb3073ae2deb4b087fa6963b30db72016e86c9cfec7de30409f57672f",
          "sha256": "08fb1ecee02f2da3cc42a787dfd19bfbe1b3dde999a25eba6e4bd215c3189fdc",
          "sha1": "bf0bf523fa7efec424ca96e585128063b4757889",
          "md5": "f2ea7a7fe4df73d712217d1974875f17"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-9.2.1-sources.jar",
          "url": "builder-9.2.1-sources.jar",
          "size": 287160,
          "sha512": "2001c492d047ea4d45292cc751d46a3389020737ed1a406bb1c5558e25e770190e903d546e607678bf64021336f172644bc944fa007a54813e19fec8dcd45d0d",
          "sha256": "0b5a4d82c0a6cdbbad271f35b0a95c13361f94182b8f5285e15eb86d69236d4b",
          "sha1": "2442ac06df995d657906142f896809979c1d7710",
          "md5": "a7232be3a688becc2e91a774b1ccb88f"
        }
      ]
    }
  ]
}
