{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "gradle-settings-api",
    "version": "9.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle-common-api",
          "version": {
            "requires": "9.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-settings-api-9.2.1.jar",
          "url": "gradle-settings-api-9.2.1.jar",
          "size": 10122,
          "sha512": "2195774deec4b0f35efd449f04b9e2e3215b2f367ec8c78d732dc3a183f2bb9c772b95ae5eb88db0bd1c26e1af868d4a3f3da6622cbd6ab7c063a56e283fb473",
          "sha256": "eaf668f7b1ec4f2975abdc6c6e2fbfb2c16471a50b5a01dabb09a00c36f98d8e",
          "sha1": "4e0c53f6663701741cc93face6fe742900860e3c",
          "md5": "2488fd8bb0c86c57ffbf6daf8f39a878"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-common-api",
          "version": {
            "requires": "9.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-settings-api-9.2.1.jar",
          "url": "gradle-settings-api-9.2.1.jar",
          "size": 10122,
          "sha512": "2195774deec4b0f35efd449f04b9e2e3215b2f367ec8c78d732dc3a183f2bb9c772b95ae5eb88db0bd1c26e1af868d4a3f3da6622cbd6ab7c063a56e283fb473",
          "sha256": "eaf668f7b1ec4f2975abdc6c6e2fbfb2c16471a50b5a01dabb09a00c36f98d8e",
          "sha1": "4e0c53f6663701741cc93face6fe742900860e3c",
          "md5": "2488fd8bb0c86c57ffbf6daf8f39a878"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-settings-api-9.2.1-javadoc.jar",
          "url": "gradle-settings-api-9.2.1-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-settings-api-9.2.1-sources.jar",
          "url": "gradle-settings-api-9.2.1-sources.jar",
          "size": 9547,
          "sha512": "e5cd599360e00ff24dcd1308da8045f0d9718e7b029e0403a0424d8e8f64ae44fc996e02e3e912d9aa26391785976703652f438aaaa015ffde37c05b36da586b",
          "sha256": "e540c7cf0045dc71bc09ee82bc7771e41c9286b5e1a2a20e3ed0c0496d81f630",
          "sha1": "a96babc790cb7c3dfc239fa0eeb753c4d2790f82",
          "md5": "1c1e725021060541dbc4b4363e19d031"
        }
      ]
    }
  ]
}
