{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlin",
    "module": "kotlin-stdlib",
    "version": "2.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "13.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-stdlib-2.3.0.jar",
          "url": "kotlin-stdlib-2.3.0.jar",
          "size": 1796996,
          "sha512": "2d19829e49ce79b8587ffc1620f95c4773ec85780f45c609017fa411064c0edbd76fc7c1333775814693258cd9c932d82bc94d18d2c545fc90198fdd3087d6a8",
          "sha256": "887587c91713250ad52fe14ad9166d042c33835049890e9437f355ffc5a195b1",
          "sha1": "ebc4eb2b6e6c91b6c844c1e3183920d86f2ef656",
          "md5": "350e6fb4b4f076fd6469e606c9f3b6e8"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "13.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-stdlib-2.3.0.jar",
          "url": "kotlin-stdlib-2.3.0.jar",
          "size": 1796996,
          "sha512": "2d19829e49ce79b8587ffc1620f95c4773ec85780f45c609017fa411064c0edbd76fc7c1333775814693258cd9c932d82bc94d18d2c545fc90198fdd3087d6a8",
          "sha256": "887587c91713250ad52fe14ad9166d042c33835049890e9437f355ffc5a195b1",
          "sha1": "ebc4eb2b6e6c91b6c844c1e3183920d86f2ef656",
          "md5": "350e6fb4b4f076fd6469e606c9f3b6e8"
        }
      ]
    },
    {
      "name": "jvmSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-stdlib-2.3.0-sources.jar",
          "url": "kotlin-stdlib-2.3.0-sources.jar",
          "size": 727775,
          "sha512": "ef5fdb5f007bf0fa63b2dfd42567298f1325c588d88b64d206650b00d6e3d23d8c04223e5eb9967b1374c9c5397b98d9e9c8aeae903d6313efe3ac5408c17145",
          "sha256": "326423198a2ad721c9c075e20db7537ad655f21bfe342a5241d874987e434531",
          "sha1": "7056b959f91689b8aaf9f1e018b010fc0c4b6f47",
          "md5": "5ba9e31cbb79885afbba3d580790026d"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-stdlib-2.3.0-all.jar",
          "url": "kotlin-stdlib-2.3.0-all.jar",
          "size": 213520,
          "sha512": "29f1dd0ad8bc7f2183e261f04a5fd1bc34f5ccf893449aad43974633c20e4686f04273cfcdf1a17792d6670c945c2fa1f3447d54f2f1041f2e6004ed5564fc32",
          "sha256": "f2d40d41c7be845b4c42c48cd30148f68366e909df822049a3de9dd152d48c02",
          "sha1": "91460e7da93f20c5f104ac7ad115f1f39080393a",
          "md5": "bdc3337271effc41b13429c01e84608c"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotlin-stdlib-2.3.0-common-sources.jar",
          "url": "kotlin-stdlib-2.3.0-common-sources.jar",
          "size": 458516,
          "sha512": "b333bc95501af78621688c99ceab13adf69c2883d14094eb566cb50dc843b3cc0eb64d548e7b4a7ea5bd88be284f30aaa0553273408902d53cc48e49fb1b09ac",
          "sha256": "66d1c81b478c6bfb64268d1c265fe949df197ffd0ac99a17ba20226accf7b300",
          "sha1": "d2cc2f99b7d7c15e0f46a6d04567a8aa028583c8",
          "md5": "50c74060630c944e9a04a0ad0e2fc6c1"
        }
      ]
    },
    {
      "name": "nativeApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.3.0"
          }
        }
      ]
    },
    {
      "name": "jsApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.klib.packaging": "packed",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlin-stdlib-js/2.3.0/kotlin-stdlib-js-2.3.0.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-stdlib-js",
        "version": "2.3.0"
      }
    },
    {
      "name": "jsRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.klib.packaging": "packed",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlin-stdlib-js/2.3.0/kotlin-stdlib-js-2.3.0.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-stdlib-js",
        "version": "2.3.0"
      }
    },
    {
      "name": "jsSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlin-stdlib-js/2.3.0/kotlin-stdlib-js-2.3.0.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-stdlib-js",
        "version": "2.3.0"
      }
    },
    {
      "name": "wasmJsApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.klib.packaging": "packed",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlin-stdlib-wasm-js/2.3.0/kotlin-stdlib-wasm-js-2.3.0.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-stdlib-wasm-js",
        "version": "2.3.0"
      }
    },
    {
      "name": "wasmJsRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.klib.packaging": "packed",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlin-stdlib-wasm-js/2.3.0/kotlin-stdlib-wasm-js-2.3.0.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-stdlib-wasm-js",
        "version": "2.3.0"
      }
    },
    {
      "name": "wasmJsSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlin-stdlib-wasm-js/2.3.0/kotlin-stdlib-wasm-js-2.3.0.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-stdlib-wasm-js",
        "version": "2.3.0"
      }
    },
    {
      "name": "wasmWasiApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.klib.packaging": "packed",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../kotlin-stdlib-wasm-wasi/2.3.0/kotlin-stdlib-wasm-wasi-2.3.0.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-stdlib-wasm-wasi",
        "version": "2.3.0"
      }
    },
    {
      "name": "wasmWasiRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.klib.packaging": "packed",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../kotlin-stdlib-wasm-wasi/2.3.0/kotlin-stdlib-wasm-wasi-2.3.0.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-stdlib-wasm-wasi",
        "version": "2.3.0"
      }
    },
    {
      "name": "wasmWasiSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../kotlin-stdlib-wasm-wasi/2.3.0/kotlin-stdlib-wasm-wasi-2.3.0.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-stdlib-wasm-wasi",
        "version": "2.3.0"
      }
    }
  ]
}
