{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "gradle",
    "version": "9.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder",
          "version": {
            "requires": "9.2.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "9.2.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "9.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-9.2.1.jar",
          "url": "gradle-9.2.1.jar",
          "size": 12974080,
          "sha512": "5eefbe5a80691053e2d082a803e671c282b1f754188e259b33ac2f45cf6dd75759d40da8d3473c28f2d743df56c0dc1a59663d936c56b565b70a261a7273e486",
          "sha256": "582e85078b60eb80669223b34b58200ba034654b2edb1cf9621e62fde7dfc0a3",
          "sha1": "db4cfe640e5a8f1de9d71ec67b5a90ac541fafc5",
          "md5": "a91ce268134f659e75eee26533af0c7b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle-settings-api",
          "version": {
            "requires": "9.2.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "32.2.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "32.2.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "repository",
          "version": {
            "requires": "32.2.1"
          }
        },
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "32.2.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "aapt2-proto",
          "version": {
            "requires": "9.2.1-15009934"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "aaptcompiler",
          "version": {
            "requires": "9.2.1"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "crash",
          "version": {
            "requires": "32.2.1"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "shared",
          "version": {
            "requires": "32.2.1"
          }
        },
        {
          "group": "com.android.tools.lint",
          "module": "lint-model",
          "version": {
            "requires": "32.2.1"
          }
        },
        {
          "group": "com.android.tools.lint",
          "module": "lint-typedef-remover",
          "version": {
            "requires": "32.2.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-compiler-common",
          "version": {
            "requires": "9.2.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "9.2.1"
          }
        },
        {
          "group": "com.android.databinding",
          "module": "baseLibrary",
          "version": {
            "requires": "9.2.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "9.2.1"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "32.2.1"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "gradle-work-action-api",
          "version": {
            "requires": "32.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpmime",
          "version": {
            "requires": "4.5.6"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.16.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.9"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.9"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.9"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.9"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "bundletool",
          "version": {
            "requires": "1.18.3"
          }
        },
        {
          "group": "com.android.tools.build.jetifier",
          "module": "jetifier-core",
          "version": {
            "requires": "1.0.0-beta10"
          }
        },
        {
          "group": "com.android.tools.build.jetifier",
          "module": "jetifier-processor",
          "version": {
            "requires": "1.0.0-beta10"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.25.5"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java-util",
          "version": {
            "requires": "3.25.5"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.tensorflow",
          "module": "tensorflow-lite-metadata",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder",
          "version": {
            "requires": "9.2.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "9.2.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "9.2.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-gradle-plugin",
          "version": {
            "requires": "2.2.10-2.0.2"
          },
          "reason": "KSP version needs to match KGP version"
        }
      ],
      "files": [
        {
          "name": "gradle-9.2.1.jar",
          "url": "gradle-9.2.1.jar",
          "size": 12974080,
          "sha512": "5eefbe5a80691053e2d082a803e671c282b1f754188e259b33ac2f45cf6dd75759d40da8d3473c28f2d743df56c0dc1a59663d936c56b565b70a261a7273e486",
          "sha256": "582e85078b60eb80669223b34b58200ba034654b2edb1cf9621e62fde7dfc0a3",
          "sha1": "db4cfe640e5a8f1de9d71ec67b5a90ac541fafc5",
          "md5": "a91ce268134f659e75eee26533af0c7b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-9.2.1-javadoc.jar",
          "url": "gradle-9.2.1-javadoc.jar",
          "size": 629635,
          "sha512": "0976aea3e5c4135b5daeb668f5c52c7a6a4bdc6dd3b57c0f32eb1c9def51a7091bdd85119c62c83ed1bce0b58101cc42e982aa0390a049b18597c8a97c2ab5da",
          "sha256": "1596056fc8e98fea531d28b99bbc9f4dc2b93cd48f22c2dba9485d50be065833",
          "sha1": "37d3caae7c4e1013c45a2775695f0d63a2f31fcb",
          "md5": "6589fc6d2c5c898b6b689bdcbe48361d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-9.2.1-sources.jar",
          "url": "gradle-9.2.1-sources.jar",
          "size": 3890524,
          "sha512": "71be2bdafee1d56df1d9f4c2d4ec5c6a0c9ad0358c65ba9eab1f3261fc46569afc56fa9158a7328e7c400bba4c74d9b01a20d9b847981598c3e247d4b41e7ea2",
          "sha256": "2b6fbf6fa80642759fa0ac32ccc6bfae2aa1d9ce27051162635dcae36eb5adcc",
          "sha1": "24a1fb15fcb13c48674978a8204e2b934268976c",
          "md5": "719cbee123226b54d192a5ba8a2ff7d3"
        }
      ]
    }
  ]
}
